---

- name: Restart django application
  supervisorctl: name={{ application_name }} state=restarted

- name: Restart celery application
  supervisorctl: name={{ celery_application_name }} state=restarted
