---

# Virtualenv settings.
enable_deadsnakes_ppa: no
recreate_virtualenv: no
virtualenv_python_version: "{{ base_python_package }}"


# Application settings.
virtualenv_path: "/home/{{ application_name }}/python-env"
project_path: "/home/{{ application_name }}/src"
application_log_dir: "/home/{{ application_name }}/logs"
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
requirements_file: "{{ project_path }}/requirements.txt"
manage_py_path: "{{ project_path }}/{{ django_project_name }}"
run_path: "/home/{{ application_name }}/run"
www_path: "/home/{{ application_name }}/www"

# Gunicorn settings.
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps


# Nginx settings.
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "/home/{{ application_name }}/static/"
nginx_media_dir: "/home/{{ application_name }}/media/"



